/* Copyright 2017-2018 Ionic Security Inc. All Rights Reserved.
 * Unauthorized use, reproduction, redistribution, modification, or disclosure is strictly prohibited.
 */

#ifndef __IONIC_ENROLLMENTERROR_H
#define	__IONIC_ENROLLMENTERROR_H

enum ISSetResponseType {
	ISSET_SUCCESS = 0,
	ISSET_ERROR_MISSING_REQUIRED_ARG,
	ISSET_ERROR_INVALIDARG_PERSISTOR_PASSWORD,
	ISSET_ERROR_COMMANDLINE_PARSE_FAILED,
	ISSET_ERROR_CONFIG_PARSE_FAILED,
	ISSET_ERROR_ASSERTIONFILE_LOAD_FAILED,
	ISSET_ERROR_DEFAULT_PERSISTOR_INVALID_FOR_LINUX,
	ISSET_ERROR_ENROLLMENT_REQUEST_FAILED,
	ISSET_ERROR_STOKEN_PARSE_FAILED,
	ISSET_ERROR_UIDAUTH_PARSE_FAILED,
	ISSET_ERROR_PUBKEY_REQUEST_FAILED,
	ISSET_ERROR_EPHEMERAL_KEYPAIR_GENERATION_FAILED,
	ISSET_ERROR_DEVICE_REGISTRATION_FAILED,
	ISSET_ERROR_PERSISTOR_SAVE_FAILED,
	ISSET_ERROR_PERSISTOR_LOAD_FAILED,
	ISSET_ERROR_INVALID_PERSISTOR,
	ISSET_ERROR_NO_API_URL,
	ISSET_ERROR_NO_PUBKEY_URL,
	ISSET_ERROR_PERSISTOR_VERSION_LENGTH,
	ISSET_ERROR_INVALID_PERSISTOR_VERSION,
	ISSET_ERROR_CONFIRMATION_FAILED,
	ISSET_ERROR_DEVICE_ID_NOTFOUND
};

#endif // __IONIC_ENROLLMENTERROR_H
